name: materim06
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.1.0
  firebase_analytics: ^12.0.3
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
